export const PASSWORD = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 64,
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBER: true,
  REQUIRE_SPECIAL: true,
  SPECIAL_CHARACTERS: '!@#$%^&*()_+-=[]{}|;:,.<>?',
  BCRYPT_ROUNDS: 12,
  RESET_TOKEN_EXPIRY_MIN: 30,
  CONTACT_CHANGE_COOLDOWN_MIN: 10,
};

export const NAME = {
  MIN_LENGTH: 2,
  MAX_LENGTH: 100,
  SHOP_MIN_LENGTH: 2,
  SHOP_MAX_LENGTH: 100,
  ADDRESS_MAX_LENGTH: 200,
  COMMENT_MAX_LENGTH: 2000,
  TITLE_MAX_LENGTH: 200,
};

export const SLUG = {
  MIN_LENGTH: 2,
  MAX_LENGTH: 120,
  SEPARATOR: '-',
  MAX_SUFFIX: 100,
};

export const PHONE = {
  MIN_LENGTH: 7,
  MAX_LENGTH: 15,
  DEFAULT_COUNTRY_CODE: '+91',
};

export const WARRANTY = {
  MAX_MONTHS: 120,
  MAX_TAGS_PER_ORDER: 20,
  MAX_TAG_LENGTH: 40,
};

export const DELIVERY_INSTRUCTIONS = {
  MAX_LENGTH: 500,
};
