export const TRACKING = {
  SESSION_TIMEOUT_MIN: 30,
  HEARTBEAT_INTERVAL_SEC: 60,
  DEVICE_FINGERPRINT_ENABLED: true,
  GEO_LOOKUP_ENABLED: true,
  BOT_FILTER_ENABLED: true,
  EVENT_BATCH_SIZE: 50,
  EVENT_FLUSH_INTERVAL_MS: 5000,
  DEDUP_WINDOW_SEC: 5,
  DEDUP_PREFIX: 'evtdup:',
  SESSION_PREFIX: 'sess:',
  REALTIME_PREFIX: 'rt:',
  REALTIME_TTL_SEC: 300,
  MAX_PAYLOAD_BYTES: 32 * 1024,
  ALLOWED_EVENTS: [
    'app_open',
    'app_install',
    'app_update',
    'signup_start',
    'signup_complete',
    'login',
    'logout',
    'product_view',
    'category_view',
    'search',
    'filter_apply',
    'add_to_cart',
    'remove_from_cart',
    'add_to_wishlist',
    'checkout_start',
    'address_add',
    'payment_init',
    'payment_success',
    'payment_fail',
    'order_placed',
    'order_cancelled',
    'order_returned',
    'review_submit',
    'coupon_apply',
    'coupon_fail',
    'share',
    'contact_click',
    'chat_open',
    'chat_send',
    'push_received',
    'push_click',
  ],
};

export const REDIS_KEYS = {
  SETTING: (key: string) => `setting:${key}`,
  SESSION: (key: string) => TRACKING.SESSION_PREFIX + key,
  CART: (userId: string) => `cart:${userId}`,
  RATE_LIMIT: (scope: string) => `rl:${scope}`,
  OTP_ATTEMPTS: (identifier: string, type: string) => `otp:att:${type}:${identifier}`,
  OTP_RESEND: (identifier: string, type: string) => `otp:resend:${type}:${identifier}`,
  OTP_DAILY: (identifier: string, date: string) => `otp:daily:${date}:${identifier}`,
  LOGIN_ATTEMPTS: (identifier: string) => `login:att:${identifier}`,
  TRACKING_DEDUP: (key: string) => TRACKING.DEDUP_PREFIX + key,
  ANALYTICS_DAILY: (date: string) => `analytics:daily:${date}`,
  REALTIME: (scope: string) => TRACKING.REALTIME_PREFIX + scope,
  TRENDING_SEARCH: () => 'search:trending',
  HOT_PRODUCT: () => 'products:hot',
  NOTIFICATION_UNREAD: (userId: string) => `notif:unread:${userId}`,
  CHAT_UNREAD: (userId: string) => `chat:unread:${userId}`,
  USER_PERMISSIONS: (role: string) => `perms:${role}`,
  UPLOAD_PRESET: (userId: string) => `upload:preset:${userId}`,
  SOCKET_ROOM: (room: string) => `sock:room:${room}`,
  MAINTENANCE: () => 'maintenance:status',
  CRON_LOCK: (name: string) => `cron:lock:${name}`,
  JOB: (jobId: string) => `job:${jobId}`,
};

export const CACHE_TTL = {
  SETTING_SEC: 300,
  PUBLIC_SETTINGS_SEC: 300,
  PRODUCT_DETAIL_SEC: 120,
  CATEGORY_LIST_SEC: 600,
  ANALYTICS_SEC: 300,
  PERMISSIONS_SEC: 600,
  DASHBOARD_SEC: 120,
} as const;
